/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ptransportation_FullscreenActivity */

#ifndef _Included_com_ptransportation_FullscreenActivity
#define _Included_com_ptransportation_FullscreenActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ptransportation_FullscreenActivity
 * Method:    cppOnSignalReceived
 * Signature: (II[B)V
 */
JNIEXPORT void JNICALL Java_com_ptransportation_FullscreenActivity_cppOnSignalReceived
  (JNIEnv *, jclass, jint, jint, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
